name: capture_photo_test_app
description: "Test camera app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  camera: ^0.11.2
  logger: ^2.6.1
  permission_handler: ^12.0.1
  flutter_styled_toast: ^2.2.1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  path: ^1.9.1
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
